name: Notificar Cambios

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar y hacer ejecutable telegram-bot-send.sh
              run: |
                curl -o /usr/local/bin/tg https://raw.githubusercontent.com/up9cloud/telegram-bot-send.sh/master/tg.ash
                chmod +x /usr/local/bin/tg
            - name: Notificar la acci칩n
              run: |
                tg \
                -T ${{ secrets.TOKEN_BOT }} \
                -I ${{ secrets.CHAT_ID }}" \
                "Actualizaci칩n en la rama Development - Realiz치 un fetch para traer los cambios m치s actualizados"
