name: Notificar Cambios

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar y hacer ejecutable telegram-bot-send.sh
              run: |
                wget https://raw.githubusercontent.com/up9cloud/telegram-bot-send.sh/master/telegram-bot-send.sh
                chmod +x telegram-bot-send.sh
            - name: Notificar la acci칩n
              run: |
                ./telegram-bot-send-sh \
                --token "{{ secrets.TOKEN_BOT }}" \
                --chatid "{{ secrets.CHAT_ID }}" \
                "Actualizaci칩n en la rama Development - Realiz치 un fetch para traer los cambios m치s actualizados"
